#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2021 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream

on:
  push:
    branches:
      - master
  schedule:
    - cron: 30 19 * 1 *

jobs:

  merge:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Merge upstream
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)          
          git remote add upstream https://github.com/coolsnowwolf/lede.git
          git fetch upstream
          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          git checkout master
          git merge --no-edit upstream/master --allow-unrelated-histories
          git push origin master
          #git checkout master
          #git merge --no-edit upstream/master
          #git push origin master
          
          #sync tag
          git fetch upstream --tags
          git push --tags
          # etc
